/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const EventType = IDL.Variant({
  'CommunityGathering' : IDL.Null,
  'Wedding' : IDL.Null,
  'ChurchEvent' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'starred' : IDL.Bool,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'eventDate' : IDL.Text,
  'eventType' : EventType,
});
export const PrayerRequest = IDL.Record({
  'id' : IDL.Nat,
  'allowOnSleeve' : IDL.Bool,
  'starred' : IDL.Bool,
  'request' : IDL.Text,
  'submittedAt' : IDL.Int,
  'firstName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDrinkImage' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteInquiry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePrayerRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAboutImageBase64' : IDL.Func([], [IDL.Text], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllPrayerRequests' : IDL.Func([], [IDL.Vec(PrayerRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContentOverrides' : IDL.Func([], [IDL.Text], ['query']),
  'getCycles' : IDL.Func([], [IDL.Nat], ['query']),
  'getDrinkImage' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getHeroImageBase64' : IDL.Func([], [IDL.Text], ['query']),
  'getInquiryById' : IDL.Func([IDL.Nat], [IDL.Opt(Inquiry)], ['query']),
  'getLogoImageBase64' : IDL.Func([], [IDL.Text], ['query']),
  'getMapAddress' : IDL.Func([], [IDL.Text], ['query']),
  'getMenuCategoriesJson' : IDL.Func([], [IDL.Text], ['query']),
  'getPrayerRequestsWithSleeveConsent' : IDL.Func(
      [],
      [IDL.Vec(PrayerRequest)],
      ['query'],
    ),
  'getSocialGridJson' : IDL.Func([], [IDL.Text], ['query']),
  'getTotalPrayerRequestsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAboutImageBase64' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveContentOverrides' : IDL.Func([IDL.Text], [], []),
  'saveDrinkImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveHeroImageBase64' : IDL.Func([IDL.Text], [], []),
  'saveLogoImageBase64' : IDL.Func([IDL.Text], [], []),
  'saveMapAddress' : IDL.Func([IDL.Text], [], []),
  'saveMenuCategoriesJson' : IDL.Func([IDL.Text], [], []),
  'saveSocialGridJson' : IDL.Func([IDL.Text], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'starInquiry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'starPrayerRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, EventType, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitPrayerRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const EventType = IDL.Variant({
    'CommunityGathering' : IDL.Null,
    'Wedding' : IDL.Null,
    'ChurchEvent' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'starred' : IDL.Bool,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'eventDate' : IDL.Text,
    'eventType' : EventType,
  });
  const PrayerRequest = IDL.Record({
    'id' : IDL.Nat,
    'allowOnSleeve' : IDL.Bool,
    'starred' : IDL.Bool,
    'request' : IDL.Text,
    'submittedAt' : IDL.Int,
    'firstName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDrinkImage' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteInquiry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePrayerRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAboutImageBase64' : IDL.Func([], [IDL.Text], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllPrayerRequests' : IDL.Func([], [IDL.Vec(PrayerRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContentOverrides' : IDL.Func([], [IDL.Text], ['query']),
    'getCycles' : IDL.Func([], [IDL.Nat], ['query']),
    'getDrinkImage' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getHeroImageBase64' : IDL.Func([], [IDL.Text], ['query']),
    'getInquiryById' : IDL.Func([IDL.Nat], [IDL.Opt(Inquiry)], ['query']),
    'getLogoImageBase64' : IDL.Func([], [IDL.Text], ['query']),
    'getMapAddress' : IDL.Func([], [IDL.Text], ['query']),
    'getMenuCategoriesJson' : IDL.Func([], [IDL.Text], ['query']),
    'getPrayerRequestsWithSleeveConsent' : IDL.Func(
        [],
        [IDL.Vec(PrayerRequest)],
        ['query'],
      ),
    'getSocialGridJson' : IDL.Func([], [IDL.Text], ['query']),
    'getTotalPrayerRequestsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAboutImageBase64' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveContentOverrides' : IDL.Func([IDL.Text], [], []),
    'saveDrinkImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveHeroImageBase64' : IDL.Func([IDL.Text], [], []),
    'saveLogoImageBase64' : IDL.Func([IDL.Text], [], []),
    'saveMapAddress' : IDL.Func([IDL.Text], [], []),
    'saveMenuCategoriesJson' : IDL.Func([IDL.Text], [], []),
    'saveSocialGridJson' : IDL.Func([IDL.Text], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'starInquiry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'starPrayerRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, EventType, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitPrayerRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };