/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type EventType = { 'CommunityGathering' : null } |
  { 'Wedding' : null } |
  { 'ChurchEvent' : null };
export interface Inquiry {
  'id' : bigint,
  'starred' : boolean,
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
  'eventDate' : string,
  'eventType' : EventType,
}
export interface PrayerRequest {
  'id' : bigint,
  'allowOnSleeve' : boolean,
  'starred' : boolean,
  'request' : string,
  'submittedAt' : bigint,
  'firstName' : string,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDrinkImage' : ActorMethod<[string], boolean>,
  'deleteInquiry' : ActorMethod<[bigint], boolean>,
  'deletePrayerRequest' : ActorMethod<[bigint], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'getAboutImageBase64' : ActorMethod<[], string>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllPrayerRequests' : ActorMethod<[], Array<PrayerRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContentOverrides' : ActorMethod<[], string>,
  'getCycles' : ActorMethod<[], bigint>,
  'getDrinkImage' : ActorMethod<[string], [] | [string]>,
  'getHeroImageBase64' : ActorMethod<[], string>,
  'getInquiryById' : ActorMethod<[bigint], [] | [Inquiry]>,
  'getLogoImageBase64' : ActorMethod<[], string>,
  'getMapAddress' : ActorMethod<[], string>,
  'getMenuCategoriesJson' : ActorMethod<[], string>,
  'getPrayerRequestsWithSleeveConsent' : ActorMethod<[], Array<PrayerRequest>>,
  'getSocialGridJson' : ActorMethod<[], string>,
  'getTotalPrayerRequestsCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveAboutImageBase64' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveContentOverrides' : ActorMethod<[string], undefined>,
  'saveDrinkImage' : ActorMethod<[string, string], undefined>,
  'saveHeroImageBase64' : ActorMethod<[string], undefined>,
  'saveLogoImageBase64' : ActorMethod<[string], undefined>,
  'saveMapAddress' : ActorMethod<[string], undefined>,
  'saveMenuCategoriesJson' : ActorMethod<[string], undefined>,
  'saveSocialGridJson' : ActorMethod<[string], undefined>,
  'schema' : ActorMethod<[], string>,
  'starInquiry' : ActorMethod<[bigint], boolean>,
  'starPrayerRequest' : ActorMethod<[bigint], boolean>,
  'submitInquiry' : ActorMethod<
    [string, string, string, EventType, string, string],
    bigint
  >,
  'submitPrayerRequest' : ActorMethod<[string, string, boolean], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];